const path = require('path')
const fs = require('fs')
const sqlite3 = require('sqlite3').verbose()

function qIdent(name) {
  return `"${String(name).replace(/"/g, '"')}"`
}

function qValue(val) {
  if (val === null || val === undefined) return 'NULL'
  if (typeof val === 'number') return Number.isFinite(val) ? String(val) : 'NULL'
  if (typeof val === 'boolean') return val ? '1' : '0'
  if (val instanceof Date) return `'${val.toISOString().replace(/'/g, "''")}'`
  // Buffer or Uint8Array -> hex literal
  if (Buffer.isBuffer(val)) return `X'${val.toString('hex')}'`
  const s = String(val)
  return `'${s.replace(/'/g, "''")}'`
}

function dbAll(db, sql, params = []) {
  return new Promise((resolve, reject) => {
    db.all(sql, params, (err, rows) => {
      if (err) reject(err)
      else resolve(rows)
    })
  })
}

async function dump() {
  const dbPath = path.resolve(__dirname, 'dev.db')
  if (!fs.existsSync(dbPath)) {
    console.error('Database file not found:', dbPath)
    process.exit(1)
  }

  const outPath = path.resolve(__dirname, 'full_dump.sql')
  const db = new sqlite3.Database(dbPath)

  const out = []
  out.push('-- SQLite full dump generated by export-sql.js')
  out.push(`-- Source: ${dbPath}`)
  out.push(`-- Date: ${new Date().toISOString()}`)
  out.push('PRAGMA foreign_keys=OFF;')
  out.push('BEGIN TRANSACTION;')

  try {
    // Read schema objects
    const objects = await dbAll(
      db,
      "SELECT type, name, tbl_name, sql FROM sqlite_master WHERE sql NOT NULL ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'view' THEN 1 WHEN 'index' THEN 2 WHEN 'trigger' THEN 3 ELSE 4 END, name"
    )

    const tables = objects.filter(o => o.type === 'table')
    const nonTables = objects.filter(o => o.type !== 'table')

    // Emit CREATE TABLE statements first
    for (const t of tables) {
      // Skip internal auto table if needed; but include everything for completeness
      if (t.name === 'sqlite_sequence') continue
      out.push(`${t.sql};`)
    }

    // For each table, emit INSERTs
    for (const t of tables) {
      if (t.name === 'sqlite_sequence') continue
      const tableName = t.name
      const colsInfo = await dbAll(db, `PRAGMA table_info(${qIdent(tableName)})`)
      const colNames = colsInfo.map(c => c.name)
      const rows = await dbAll(db, `SELECT * FROM ${qIdent(tableName)}`)
      if (rows.length === 0) continue
      for (const row of rows) {
        const values = colNames.map(c => qValue(row[c]))
        out.push(`INSERT INTO ${qIdent(tableName)} (${colNames.map(qIdent).join(', ')}) VALUES (${values.join(', ')});`)
      }
    }

    // Emit indexes, views, triggers
    for (const o of nonTables) {
      out.push(`${o.sql};`)
    }

    out.push('COMMIT;')

    fs.writeFileSync(outPath, out.join('\n') + '\n', 'utf8')
    console.log('SQL dump written to:', outPath)
  } catch (err) {
    console.error('Failed to export SQL:', err)
    process.exitCode = 1
  } finally {
    db.close()
  }
}

dump()

